language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wheatman999/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true wheatman999/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-960051134654"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

# DdnxVYxKRntVV6+tRzSiJRAdlTh9f4RxescY7Jyd